// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/go-kratos/kratos/v2"
	"leo/internal/data"
	"leo/internal/server"
	"leo/internal/service"
)

import (
	_ "go.uber.org/automaxprocs"
)

// Injectors from wire.go:

// wireApp init kratos application.
func wireApp() (*kratos.App, func(), error) {
	dataData, cleanup, err := data.NewData()
	if err != nil {
		return nil, nil, err
	}
	snippetService := service.NewSnippetService(dataData)
	grpcServer, err := server.NewGRPCServer(snippetService)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	app := newApp(grpcServer)
	return app, func() {
		cleanup()
	}, nil
}
