// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v4.24.2
// source: api/snippet/v1/snippet.proto

package snippet

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Request struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value         string                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Request) Reset() {
	*x = Request{}
	mi := &file_api_snippet_v1_snippet_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Request) ProtoMessage() {}

func (x *Request) ProtoReflect() protoreflect.Message {
	mi := &file_api_snippet_v1_snippet_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Request.ProtoReflect.Descriptor instead.
func (*Request) Descriptor() ([]byte, []int) {
	return file_api_snippet_v1_snippet_proto_rawDescGZIP(), []int{0}
}

func (x *Request) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *Request) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type Response struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Pairs         []*Response_Pair       `protobuf:"bytes,1,rep,name=pairs,proto3" json:"pairs,omitempty"`
	Code          int32                  `protobuf:"varint,2,opt,name=code,proto3" json:"code,omitempty"`
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Response) Reset() {
	*x = Response{}
	mi := &file_api_snippet_v1_snippet_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Response) ProtoMessage() {}

func (x *Response) ProtoReflect() protoreflect.Message {
	mi := &file_api_snippet_v1_snippet_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Response.ProtoReflect.Descriptor instead.
func (*Response) Descriptor() ([]byte, []int) {
	return file_api_snippet_v1_snippet_proto_rawDescGZIP(), []int{1}
}

func (x *Response) GetPairs() []*Response_Pair {
	if x != nil {
		return x.Pairs
	}
	return nil
}

func (x *Response) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *Response) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type Response_Pair struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value         string                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Response_Pair) Reset() {
	*x = Response_Pair{}
	mi := &file_api_snippet_v1_snippet_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Response_Pair) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Response_Pair) ProtoMessage() {}

func (x *Response_Pair) ProtoReflect() protoreflect.Message {
	mi := &file_api_snippet_v1_snippet_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Response_Pair.ProtoReflect.Descriptor instead.
func (*Response_Pair) Descriptor() ([]byte, []int) {
	return file_api_snippet_v1_snippet_proto_rawDescGZIP(), []int{1, 0}
}

func (x *Response_Pair) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *Response_Pair) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

var File_api_snippet_v1_snippet_proto protoreflect.FileDescriptor

const file_api_snippet_v1_snippet_proto_rawDesc = "" +
	"\n" +
	"\x1capi/snippet/v1/snippet.proto\x12\rapi.router.v1\"1\n" +
	"\aRequest\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value\"\x9c\x01\n" +
	"\bResponse\x122\n" +
	"\x05pairs\x18\x01 \x03(\v2\x1c.api.router.v1.Response.PairR\x05pairs\x12\x12\n" +
	"\x04code\x18\x02 \x01(\x05R\x04code\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\x1a.\n" +
	"\x04Pair\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value2\xb6\x01\n" +
	"\aSnippet\x128\n" +
	"\x05Query\x12\x16.api.router.v1.Request\x1a\x17.api.router.v1.Response\x126\n" +
	"\x03Put\x12\x16.api.router.v1.Request\x1a\x17.api.router.v1.Response\x129\n" +
	"\x06Delete\x12\x16.api.router.v1.Request\x1a\x17.api.router.v1.ResponseB+\n" +
	"\vapi.live.v1P\x01Z\x1aleo/api/snippet/v1;snippetb\x06proto3"

var (
	file_api_snippet_v1_snippet_proto_rawDescOnce sync.Once
	file_api_snippet_v1_snippet_proto_rawDescData []byte
)

func file_api_snippet_v1_snippet_proto_rawDescGZIP() []byte {
	file_api_snippet_v1_snippet_proto_rawDescOnce.Do(func() {
		file_api_snippet_v1_snippet_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_snippet_v1_snippet_proto_rawDesc), len(file_api_snippet_v1_snippet_proto_rawDesc)))
	})
	return file_api_snippet_v1_snippet_proto_rawDescData
}

var file_api_snippet_v1_snippet_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_api_snippet_v1_snippet_proto_goTypes = []any{
	(*Request)(nil),       // 0: api.router.v1.Request
	(*Response)(nil),      // 1: api.router.v1.Response
	(*Response_Pair)(nil), // 2: api.router.v1.Response.Pair
}
var file_api_snippet_v1_snippet_proto_depIdxs = []int32{
	2, // 0: api.router.v1.Response.pairs:type_name -> api.router.v1.Response.Pair
	0, // 1: api.router.v1.Snippet.Query:input_type -> api.router.v1.Request
	0, // 2: api.router.v1.Snippet.Put:input_type -> api.router.v1.Request
	0, // 3: api.router.v1.Snippet.Delete:input_type -> api.router.v1.Request
	1, // 4: api.router.v1.Snippet.Query:output_type -> api.router.v1.Response
	1, // 5: api.router.v1.Snippet.Put:output_type -> api.router.v1.Response
	1, // 6: api.router.v1.Snippet.Delete:output_type -> api.router.v1.Response
	4, // [4:7] is the sub-list for method output_type
	1, // [1:4] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_api_snippet_v1_snippet_proto_init() }
func file_api_snippet_v1_snippet_proto_init() {
	if File_api_snippet_v1_snippet_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_snippet_v1_snippet_proto_rawDesc), len(file_api_snippet_v1_snippet_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_snippet_v1_snippet_proto_goTypes,
		DependencyIndexes: file_api_snippet_v1_snippet_proto_depIdxs,
		MessageInfos:      file_api_snippet_v1_snippet_proto_msgTypes,
	}.Build()
	File_api_snippet_v1_snippet_proto = out.File
	file_api_snippet_v1_snippet_proto_goTypes = nil
	file_api_snippet_v1_snippet_proto_depIdxs = nil
}
